In [1]:
import pandas as pd
import requests
import json

In [13]:
URL = "https://service-index-ai.ethics.hse.ru"

# RSPP

In [3]:
df = pd.read_csv("results.csv", index_col=0)
df.head()

,year,company,Unnamed: 0topics,Экология в целом,Климат,Энергия,Воздух,Вода,Отходы и циклическая экономика,Биоразнообразие,...,Этика,Корпоративное управление,Устойчивое развитие,!Кибербезопасность,env,gov,social,all_letters,avg,on_letters
0,2004.0,АО «Группа «Илим»,2.670868e+06,0.000000,0.005321,0.012626,0.003872,0.030120,0.020988,0.015211,...,0.000000,0.003489,0.006082,0.0,0.50,0.67,0.56,0.56,0.576667,1.00
1,2004.0,ОАО «Рязанская ГРЭС»,2.670694e+06,0.000000,0.000000,0.000000,0.031644,0.028729,0.023511,0.015468,...,0.000000,0.000000,0.000000,0.0,0.50,0.33,0.44,0.44,0.423333,0.00
8,2006,ОАО «ТГК-6»,3.071506e+06,0.012101,0.012886,0.052351,0.018976,0.026239,0.012565,0.003150,...,0.000000,0.010256,0.006888,0.0,0.47,0.48,0.39,0.43,0.446667,0.85
6,2006,ОАО «Волжская ТГК»,3.074424e+06,0.003978,0.012979,0.059898,0.026394,0.026344,0.022817,0.009506,...,0.000000,0.009659,0.007815,0.0,0.43,0.49,0.38,0.41,0.433333,0.81
2,2006,BP p.l.c.,3.075012e+06,0.012450,0.045558,0.028783,0.009554,0.006310,0.008558,0.005282,...,0.002169,0.002895,0.021662,0.0,0.38,0.53,0.37,0.40,0.426667,0.77

In [4]:
companies = df["company"].unique().tolist()

In [5]:
js_companies = []
for company in companies:
    js_companies.append({"name": company, "company_type_id": 1})

In [14]:
res = requests.post(f"{URL}/topsis/company", json={"data": js_companies})
res

In [16]:
company_id = {company["name"]: company["id"] for company in res.json()["data"]}

In [17]:
for key in company_id.keys():
    if key not in companies:
        print(key)

In [18]:
df.fillna(0, inplace=True)

In [19]:
topsis_data = []
for _, row in df.iterrows():
    years = row["year"].split(",")
    for year in years:
        topsis_data.append(
            {
                "company_id": company_id[row["company"]],
                "year": int(float(year)),
                "environmental": row["env"],
                "social": row["social"],
                "governance": row["gov"],
                "on_letters": row["on_letters"],
                "all_topics": row["all_letters"],
                "average": row["avg"],
            }
        )

In [20]:
res = requests.post(f"{URL}/topsis/topsis", json={"data": topsis_data})
res

# Banks

In [21]:
df = pd.read_csv("workflow/banks_results.csv", index_col=0)
df.head()

,year,company,Экология в целом,Климат,Энергия,Воздух,Вода,Отходы и циклическая экономика,Биоразнообразие,Рекультивация земель,...,Устойчивое развитие_base_words_count,!Кибербезопасность_percent_of_words,!Кибербезопасность_importance,!Кибербезопасность_base_words_count,env,gov,social,avg,on_letters,all_letters
index,,,,,,,,,,,,,,,,,,,,,
1978,2020,"ПАО ""МОСКОВСКИЙ КРЕДИТНЫЙ БАНК""",0.006946,0.004917,0.005623,0.004854,0.008042,0.004554,0.001790,0.002236,...,1.064015,0.005184,0.0,0.064472,0.44,0.35,0.55,0.446667,0.67,0.49
2590,2020,"ПАО ""АК БАРС"" БАНК",0.028138,0.002301,0.002888,0.016649,0.015065,0.002624,0.000879,0.000564,...,0.676010,0.004073,0.0,0.055107,0.50,0.28,0.55,0.443333,0.65,0.50
2272,2020,ПАО РОСБАНК,0.000000,0.000000,0.009549,0.001790,0.000000,0.002408,0.003993,0.006850,...,2.934783,0.002504,0.0,0.094203,0.47,0.39,0.39,0.416667,0.63,0.41
1000,2020,Банк ВТБ (ПАО),0.017305,0.003102,0.003155,0.011062,0.012205,0.002650,0.002739,0.001134,...,0.555881,0.002323,0.0,0.028045,0.45,0.24,0.48,0.390000,0.57,0.44
963,2020,"ПАО ""Совкомбанк""",0.023276,0.006965,0.002361,0.015026,0.014051,0.000616,0.000581,0.000926,...,0.457286,0.002235,0.0,0.033291,0.50,0.24,0.37,0.370000,0.53,0.39

In [22]:
companies = df["company"].unique().tolist()

In [23]:
js_companies = []
for company in companies:
    js_companies.append({"name": company, "company_type_id": 2})

In [24]:
res = requests.post(f"{URL}/topsis/company", json={"data": js_companies})
res

In [25]:
company_id = {company["name"]: company["id"] for company in res.json()["data"]}

In [26]:
for key in company_id.keys():
    if key not in companies:
        print(key)

In [27]:
df.fillna(0, inplace=True)

In [28]:
topsis_data = []
for _, row in df.iterrows():
    topsis_data.append(
        {
            "company_id": company_id[row["company"]],
            "year": int(row["year"]),
            "environmental": row["env"],
            "social": row["social"],
            "governance": row["gov"],
            "on_letters": row["on_letters"],
            "all_topics": row["all_letters"],
            "average": row["avg"],
        }
    )

In [29]:
res = requests.post(f"{URL}/topsis/topsis", json={"data": topsis_data})
res