In [2]:
import pandas as pd

In [10]:
topics = pd.read_csv("topics.csv.zip", index_col=0)
topics.head()

                           0
0               Оплата труда
1         Трудовые отношения
2                  Лидерство
3  Отношения с потребителями
4                  Лидерство

In [14]:
df = pd.read_csv("../topics/paragrapghs_with_topisc.csv.zip", usecols=['company', 'year', 'sector', 'report_type', 'paragraph',
       'original_text', 'cleaned_text','max_score', 'max_topic'])
df = df[df["cleaned_text"].notna()]
# df = df[df["cleaned_text"].apply(lambda x: len(x.split()) > 1)]
# df = df.reset_index(drop=True)
df.head()

/tmp/ipykernel_10822/3045519590.py:1: DtypeWarning: Columns (3,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../topics/paragrapghs_with_topisc.csv.zip", usecols=['company', 'year', 'sector', 'report_type', 'paragraph',

,company,year,sector,report_type,paragraph,original_text,cleaned_text,max_score,max_topic
0,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,0.0,1 ММК,ммк,NaN,NaN
1,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,1.0,СОЦИАЛЬНЫЙ ОТЧЕТ ММК ЗА 2014 ГОД МАГНИТОГОРСКИ...,социальный отчёт ммк за год магнитогорский мет...,0.087370,Оплата труда
2,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,3.0,СОДЕРЖАНИЕ,содержание,0.219529,Экология
3,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,4.0,Обращение председателя совета директоров.........,обращение председатель совет директор параметр...,NaN,NaN
4,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,5.0,3 ММК,ммк,0.102598,Отношения с потребителями

In [15]:
df.shape, topics.shape

((2309485, 9), (1963163, 1))

In [9]:
df["new_topics"] = topics
df.head()

,company,year,sector,report_type,paragraph,original_text,cleaned_text,max_score,max_topic,new_topics
1,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,4.0,Обращение председателя совета директоров.........,обращение председатель совет директор параметр...,0.260378,Экология,Трудовые отношения
3,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,7.0,и сервисных услуг. Мы практически завершили дл...,сервисный услуга мы практически завершить длит...,0.130189,Экология,Отношения с потребителями
9,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,14.0,Наша компания входит в число российских предпр...,наш компания входить число российский предприя...,0.130189,Экология,Отчетность и прозрачность
11,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,16.0,Компания разрабатывает и успешно внедряет соци...,компания разрабатывать успешно внедрять социал...,0.092450,Климат,Безопасность и охрана труда
12,ПАО «ММК»,2014,Металлургическая и горнодобывающая,СО,17.0,Российский союз промышленников и предпринимате...,российский союз промышленник предприниматель д...,0.130744,Климат,Отчетность и прозрачность