### Данные РСПП

[Индексы РСПП](https://rspp.ru/upload/content/242/zyin6mfuo00qqipt1q5ekna5j8ambq4q/Indeksy-RSPP_v02.pdf)

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [3]:
rspp_df = pd.read_csv('../data/RSPP rating - Индекс _Ответственность и открытость_.csv')
rspp_df.head()

   year                                          companies letter
0  2017  АЛРОСА, «ИнтерРАО», ЛУКОЙЛ, «Металлоинвест», «...      A
1  2017  «Аэрофлот», «Газпром», «ЕвроХим», «Зарубежнефт...      B
2  2018  АЛРОСА, «Газпром», «Зарубежнефть», ЛУКОЙЛ, «Ме...      A
3  2018  «Аэрофлот», ЕВРАЗ, «ЕвроХим», «Интер РАО», ММК...      B
4  2019  АЛРОСА, «Газпром», «Интер РАО», ЛУКОЙЛ, «Метал...      A

In [4]:
rspp_df.companies = rspp_df.companies.apply(lambda x: x.split(', '))
rspp_df = rspp_df.explode('companies').reset_index(drop=True)
rspp_df = rspp_df.rename(columns={'companies': 'company'})
rspp_df.year = rspp_df.year.astype('int')
rspp_df.head()

   year              company letter
0  2017               АЛРОСА      A
1  2017           «ИнтерРАО»      A
2  2017               ЛУКОЙЛ      A
3  2017      «Металлоинвест»      A
4  2017  «Норильский никель»      A

In [6]:
rspp_df = pd.read_csv('../data/rspp - rspp.csv')
rspp_df = rspp_df.drop(['company'], axis=1).rename(columns={'компания РСПП': 'компания',
                                                            'year': 'год'})
rspp_df.head()

    год letter                      компания
0  2017      A                   АК «АЛРОСА»
1  2017      A           ПАО «ИНТЕР РАО ЕЭС»
2  2017      A                  ПАО «ЛУКОЙЛ»
3  2017      A               «МЕТАЛЛОИНВЕСТ»
4  2017      A  ПАО «ГМК «Норильский никель»

### Наши данные

In [8]:
df = pd.read_csv('../data/reports_info_esg2.csv', index_col=0)
df = df.drop(['сектор', 'тип отчета', 'ссылка на отчет'], axis=1)

In [9]:
df[df['год'].apply(len) > 4].head()

,компания,год,E_Общие,E_Биоразнообразие,E_Вода,E_Газ,E_Климат,E_Отходы,E_Экологический менеджмент,E_Энергия,...,S_Охрана здоровья,S_Профсоюзы и коллективные договоры,S_Трудовые отношения,G_Антикоррупция,G_Дивиденды и акционеры,G_Инновации,G_Лидерство,G_Отчетность и прозрачность,G_Управление рисками,G_Эффективность и производительность
27,Abbott,"2013, 2012",0.02,0.01,0.00,0.0,0.01,0.01,0.01,0.01,...,0.10,0.02,0.04,0.02,0.02,0.01,0.03,0.04,0.02,0.03
32,BIOCAD,"2021, 2020",0.04,0.03,0.02,0.0,0.02,0.02,0.02,0.02,...,0.06,0.03,0.05,0.04,0.02,0.02,0.04,0.05,0.03,0.04
33,BIOCAD,"2019, 2018",0.05,0.04,0.01,0.0,0.02,0.03,0.02,0.01,...,0.07,0.03,0.06,0.04,0.02,0.03,0.04,0.04,0.02,0.04
46,«Coca-Cola HBC Россия»,"2016, 2015",0.03,0.01,0.02,0.0,0.02,0.02,0.02,0.02,...,0.00,0.02,0.03,0.02,0.02,0.00,0.02,0.02,0.02,0.06
70,Компания EY,"2016, 2015",0.02,0.01,0.00,0.0,0.02,0.01,0.02,0.02,...,0.00,0.04,0.07,0.04,0.03,0.02,0.06,0.05,0.02,0.05

In [10]:
2013, 2012

(2013, 2012)

In [12]:
df = pd.read_csv('../data/reports_info_esg2.csv', index_col=0)
df = df.drop(['сектор', 'тип отчета', 'ссылка на отчет'], axis=1)
# df = df[df['год'].apply(len) == 4]
df['год'] = df['год'].apply(lambda x: x.split(', '))
df = df.explode('год').reset_index(drop=True)
df['год'] = df['год'].astype(int)
df = df.groupby(by=['компания', 'год']).sum().reset_index()
df.head()

,компания,год,E_Общие,E_Биоразнообразие,E_Вода,E_Газ,E_Климат,E_Отходы,E_Экологический менеджмент,E_Энергия,...,S_Охрана здоровья,S_Профсоюзы и коллективные договоры,S_Трудовые отношения,G_Антикоррупция,G_Дивиденды и акционеры,G_Инновации,G_Лидерство,G_Отчетность и прозрачность,G_Управление рисками,G_Эффективность и производительность
0,Abbott,2012,0.02,0.01,0.00,0.00,0.01,0.01,0.01,0.01,...,0.10,0.02,0.04,0.02,0.02,0.01,0.03,0.04,0.02,0.03
1,Abbott,2013,0.02,0.01,0.00,0.00,0.01,0.01,0.01,0.01,...,0.10,0.02,0.04,0.02,0.02,0.01,0.03,0.04,0.02,0.03
2,"Alcoa, Inc.",2004,0.02,0.01,0.01,0.00,0.01,0.03,0.01,0.01,...,0.00,0.03,0.03,0.02,0.02,0.00,0.02,0.02,0.02,0.03
3,"Alcoa, Inc.",2006,0.05,0.02,0.02,0.01,0.02,0.01,0.03,0.03,...,0.01,0.04,0.06,0.03,0.04,0.01,0.04,0.05,0.03,0.05
4,BELUGA GROUP,2020,0.04,0.01,0.02,0.00,0.03,0.02,0.03,0.03,...,0.01,0.05,0.07,0.05,0.03,0.02,0.06,0.06,0.03,0.05

### Topsis

In [13]:
class Topsis:
    evaluation_matrix = np.array([])  # Matrix
    weighted_normalized = np.array([])  # Weight matrix
    normalized_decision = np.array([])  # Normalisation matrix

    '''
	Create an evaluation matrix consisting of m alternatives and n criteria,
	with the intersection of each alternative and criteria given as {\displaystyle x_{ij}}x_{ij},
	we therefore have a matrix {\displaystyle (x_{ij})_{m\times n}}(x_{{ij}})_{{m\times n}}.
	'''

    def __init__(self, evaluation_matrix, weight_matrix, criteria):
        # M×N matrix
        self.evaluation_matrix = np.array(evaluation_matrix, dtype="float")

        # M alternatives (options)
        self.row_size = len(self.evaluation_matrix)

        # N attributes/criteria
        self.column_size = len(self.evaluation_matrix[0])

        # N size weight matrix
        self.weight_matrix = np.array(weight_matrix, dtype="float")
        self.weight_matrix = self.weight_matrix/sum(self.weight_matrix)
        self.criteria = np.array(criteria, dtype="float")

    '''
	# Step 2
	The matrix {\displaystyle (x_{ij})_{m\times n}}(x_{{ij}})_{{m\times n}} is then normalised to form the matrix
	'''

    def step_2(self):
        # normalized scores
        self.normalized_decision = np.copy(self.evaluation_matrix)
        sqrd_sum = np.zeros(self.column_size)
        for i in range(self.row_size):
            for j in range(self.column_size):
                sqrd_sum[j] += self.evaluation_matrix[i, j]**2
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.normalized_decision[i,
                                         j] = self.evaluation_matrix[i, j]/(sqrd_sum[j]**0.5)

    '''
	# Step 3
	Calculate the weighted normalised decision matrix
	'''

    def step_3(self):
        self.weighted_normalized = np.copy(self.normalized_decision)
        for i in range(self.row_size):
            for j in range(self.column_size):
                self.weighted_normalized[i, j] *= self.weight_matrix[j]

    '''
	# Step 4
	Determine the worst alternative {\displaystyle (A_{w})}(A_{w}) and the best alternative {\displaystyle (A_{b})}(A_{b}):
	'''

    def step_4(self):
        self.worst_alternatives = np.zeros(self.column_size)
        self.best_alternatives = np.zeros(self.column_size)
        for i in range(self.column_size):
            if self.criteria[i]:
                self.worst_alternatives[i] = min(
                    self.weighted_normalized[:, i])
                self.best_alternatives[i] = max(self.weighted_normalized[:, i])
            else:
                self.worst_alternatives[i] = max(
                    self.weighted_normalized[:, i])
                self.best_alternatives[i] = min(self.weighted_normalized[:, i])

    '''
	# Step 5
	Calculate the L2-distance between the target alternative {\displaystyle i}i and the worst condition {\displaystyle A_{w}}A_{w}
	{\displaystyle d_{iw}={\sqrt {\sum _{j=1}^{n}(t_{ij}-t_{wj})^{2}}},\quad i=1,2,\ldots ,m,}
	and the distance between the alternative {\displaystyle i}i and the best condition {\displaystyle A_{b}}A_b
	{\displaystyle d_{ib}={\sqrt {\sum _{j=1}^{n}(t_{ij}-t_{bj})^{2}}},\quad i=1,2,\ldots ,m}
	where {\displaystyle d_{iw}}d_{{iw}} and {\displaystyle d_{ib}}d_{{ib}} are L2-norm distances 
	from the target alternative {\displaystyle i}i to the worst and best conditions, respectively.
	'''

    def step_5(self):
        self.worst_distance = np.zeros(self.row_size)
        self.best_distance = np.zeros(self.row_size)

        self.worst_distance_mat = np.copy(self.weighted_normalized)
        self.best_distance_mat = np.copy(self.weighted_normalized)

        for i in range(self.row_size):
            for j in range(self.column_size):
                self.worst_distance_mat[i][j] = (self.weighted_normalized[i][j]-self.worst_alternatives[j])**2
                self.best_distance_mat[i][j] = (self.weighted_normalized[i][j]-self.best_alternatives[j])**2
                
                self.worst_distance[i] += self.worst_distance_mat[i][j]
                self.best_distance[i] += self.best_distance_mat[i][j]

        for i in range(self.row_size):
            self.worst_distance[i] = self.worst_distance[i]**0.5
            self.best_distance[i] = self.best_distance[i]**0.5

    '''
	# Step 6
	Calculate the similarity
	'''

    def step_6(self):
        np.seterr(all='ignore')
        self.worst_similarity = np.zeros(self.row_size)
        self.best_similarity = np.zeros(self.row_size)

        for i in range(self.row_size):
            # calculate the similarity to the worst condition
            self.worst_similarity[i] = self.worst_distance[i] / \
                (self.worst_distance[i]+self.best_distance[i])

            # calculate the similarity to the best condition
            self.best_similarity[i] = self.best_distance[i] / \
                (self.worst_distance[i]+self.best_distance[i])
    
    def ranking(self, data):
        return [i+1 for i in data.argsort()]

    def rank_to_worst_similarity(self):
        # return rankdata(self.worst_similarity, method="min").astype(int)
        return self.ranking(self.worst_similarity)

    def rank_to_best_similarity(self):
        # return rankdata(self.best_similarity, method='min').astype(int)
        return self.ranking(self.best_similarity)
    
    @property
    def s_plus(self):
        # расстояние до лучшей альтерантивы
        return self.best_similarity
    
    @property
    def s_minus(self):
        # расстояние до худщей альтернативы
        return self.worst_similarity

    def calc(self):
        self.step_2()
        self.step_3()
        self.step_4()
        self.step_5()
        self.step_6()

In [14]:
e_topics = ['E_Биоразнообразие', 'E_Вода', 'E_Газ', 
            'E_Климат', 'E_Отходы', 'E_Экологический менеджмент',
            'E_Энергия', 'E_Общие']
s_topics = ['S_Безопасность и охрана здоровья', 'S_Безопасность продукта',
            'S_Благотворительность', 'S_Инвестиции и капитальные вложения',
            'S_Налоги', 'S_Обучение и развитие', 'S_Оплата труда',
            'S_Отношения с потребителями', 'S_Отношения с работниками',
            'S_Охрана здоровья', 'S_Профсоюзы и коллективные договоры',
            'S_Трудовые отношения']
g_topics = ['G_Антикоррупция', 'G_Дивиденды и акционеры',
            'G_Инновации', 'G_Лидерство', 'G_Отчетность и прозрачность',
            'G_Управление рисками', 'G_Эффективность и производительность']

In [15]:
df_year_grouped = df.groupby('год')
for year, df_group in df_year_grouped:
    evaluation_matrix = df_group[e_topics + s_topics + g_topics].to_numpy()
    
    weights = np.ones(evaluation_matrix.shape[1])
    criterias = np.ones(evaluation_matrix.shape[1])
    
    t = Topsis(evaluation_matrix, weights, criterias)
    
    t.calc()
    
    
    df.loc[df['год'] == year, 's+'] = t.s_plus
    df.loc[df['год'] == year, 's-'] = t.s_minus

/tmp/ipykernel_15618/1078065941.py:42: RuntimeWarning: invalid value encountered in double_scalars
  j] = self.evaluation_matrix[i, j]/(sqrd_sum[j]**0.5)

In [16]:
# s+ - расстояние до лучшей альтернативы
# s- - расстояние до худшей альтернативы
df = df[['компания', 'год', 's-']]
df = df[(df['год'] >= 2017) & df['компания'].isin(
    rspp_df['компания'].unique()
)].reset_index(drop=True)
df.head()

           компания   год        s-
0   X5 Retail Group  2018  0.256976
1   X5 Retail Group  2019  0.402535
2   X5 Retail Group  2020  0.340841
3   X5 Retail Group  2021  0.280810
4  «Банк ВТБ» (ПАО)  2017  0.164680

In [17]:
df.shape

(206, 3)

In [18]:
df = pd.merge(df, rspp_df, on=['компания', 'год'], how='inner')
df.head()

           компания   год        s- letter
0   X5 Retail Group  2021  0.280810      B
1  «Банк ВТБ» (ПАО)  2020  0.261009      B
2   «МЕТАЛЛОИНВЕСТ»  2017  0.277275      A
3   «МЕТАЛЛОИНВЕСТ»  2018  0.181905      A
4   «МЕТАЛЛОИНВЕСТ»  2019  0.280332      A

In [19]:
df.shape

(155, 4)

In [20]:
df.head(15)

             компания   год        s- letter
0     X5 Retail Group  2021  0.280810      B
1    «Банк ВТБ» (ПАО)  2020  0.261009      B
2     «МЕТАЛЛОИНВЕСТ»  2017  0.277275      A
3     «МЕТАЛЛОИНВЕСТ»  2018  0.181905      A
4     «МЕТАЛЛОИНВЕСТ»  2019  0.280332      A
5     «МЕТАЛЛОИНВЕСТ»  2020  0.299296      A
6     «МЕТАЛЛОИНВЕСТ»  2021  0.351157      A
7   «Сахалин Энерджи»  2017  0.311104      B
8   «Сахалин Энерджи»  2018  0.284807      B
9   «Сахалин Энерджи»  2019  0.285659      B
10  «Сахалин Энерджи»  2020  0.307583      B
11        АК «АЛРОСА»  2017  0.180964      A
12        АК «АЛРОСА»  2018  0.282258      A
13        АК «АЛРОСА»  2019  0.302191      A
14        АК «АЛРОСА»  2020  0.329526      A

In [21]:
df.groupby(by=['letter', 'год'])

In [22]:
for (letter, year), df_grouped in df.groupby(by=['letter', 'год']):
    print(
        f'{year} - {letter} - {df_grouped["s-"].min()} - {df_grouped["s-"].max()}'
    )

2017 - A - 0.1809638807588218 - 0.39101357232659983
2018 - A - 0.16881358528556206 - 0.48047869181640795
2019 - A - 0.18486676264393972 - 0.4796685764083596
2020 - A - 0.11694239169647286 - 0.5248861351256443
2021 - A - 0.0701964694659694 - 0.6032720015811712
2017 - B - 0.08154819454853751 - 0.5306755823378808
2018 - B - 0.0 - 0.3607629586478078
2019 - B - 0.11128687945307432 - 0.46788611055862717
2020 - B - 0.03412648116502029 - 0.4702439667849237
2021 - B - 0.0 - 0.4173144693275768
2021 - B+ - 0.021832983541124614 - 0.34351756895219926
2021 - C - 0.38911157529657253 - 0.5506395027407772

In [194]:
df.head(155)

             компания   год        s- letter
0     X5 Retail Group  2021  0.280810      B
1    «Банк ВТБ» (ПАО)  2020  0.261009      B
2     «МЕТАЛЛОИНВЕСТ»  2017  0.277275      A
3     «МЕТАЛЛОИНВЕСТ»  2018  0.181905      A
4     «МЕТАЛЛОИНВЕСТ»  2019  0.280332      A
..                ...   ...       ...    ...
150     ПАО «ФосАгро»  2018  0.263061      B
151     ПАО «ФосАгро»  2019  0.295678      B
152     ПАО «ФосАгро»  2020  0.275017      B
153     ПАО «ФосАгро»  2021  0.291269      A
154     Петропавловск  2020  0.284767      B

[155 rows x 4 columns]

In [195]:
for year, df_grouped in df.groupby(by=['год']):
    print(year)
    print(df_grouped.sort_values(by=['letter']))
    print()

2017
                         компания   год        s- letter
2                 «МЕТАЛЛОИНВЕСТ»  2017  0.277275      A
134              ПАО «Северсталь»  2017  0.265886      A
125           ПАО «СИБУР-Холдинг»  2017  0.258348      A
93             ПАО «НК «Роснефть»  2017  0.391014      A
81                   ПАО «ЛУКОЙЛ»  2017  0.242874      A
64   ПАО «ГМК «Норильский никель»  2017  0.250465      A
53                       ОК РУСАЛ  2017  0.244436      A
74            ПАО «ИНТЕР РАО ЕЭС»  2017  0.181843      A
36        Госкорпорация «Росатом»  2017  0.257266      A
27                      АО «СУЭК»  2017  0.229966      A
11                    АК «АЛРОСА»  2017  0.180964      A
7               «Сахалин Энерджи»  2017  0.311104      B
129        ПАО «Сбербанк России»   2017  0.303328      B
120                ПАО «РусГидро»  2017  0.213157      B
115              ПАО «Ростелеком»  2017  0.186715      B
103                 ПАО «НОВАТЭК»  2017  0.290587      B
98                     ПАО «НЛМК»  2017  0.247436      B
16              АО «Зарубежнефть»  2017  0.238574      B
88                      ПАО «МТС»  2017  0.190403      B
18              АО «МХК «ЕвроХим»  2017  0.280272      B
78                    ПАО «КАМАЗ»  2017  0.081548      B
145              ПАО «Транснефть»  2017  0.162555      B
68                  ПАО «Газпром»  2017  0.530676      B
58                 ПАО «АЭРОФЛОТ»  2017  0.171937      B
47                      ОАО «РЖД»  2017  0.239318      B
148               ПАО «Уралкалий»  2017  0.298881      B

2018
                         компания   год        s- letter
3                 «МЕТАЛЛОИНВЕСТ»  2018  0.181905      A
82                   ПАО «ЛУКОЙЛ»  2018  0.213199      A
69                  ПАО «Газпром»  2018  0.480479      A
65   ПАО «ГМК «Норильский никель»  2018  0.227648      A
116              ПАО «Ростелеком»  2018  0.171564      A
32                  АФК «Система»  2018  0.449490      A
126           ПАО «СИБУР-Холдинг»  2018  0.244603      A
135              ПАО «Северсталь»  2018  0.215979      A
17              АО «Зарубежнефть»  2018  0.168814      A
12                    АК «АЛРОСА»  2018  0.282258      A
28                      АО «СУЭК»  2018  0.214516      A
94             ПАО «НК «Роснефть»  2018  0.375413      A
130        ПАО «Сбербанк России»   2018  0.287597      B
99                     ПАО «НЛМК»  2018  0.235035      B
121                ПАО «РусГидро»  2018  0.223195      B
110                   ПАО «Полюс»  2018  0.000000      B
104                 ПАО «НОВАТЭК»  2018  0.233985      B
139                     ПАО «ТМК»  2018  0.125010      B
75            ПАО «ИНТЕР РАО ЕЭС»  2018  0.228714      B
146              ПАО «Транснефть»  2018  0.149107      B
59                 ПАО «АЭРОФЛОТ»  2018  0.186886      B
54                       ОК РУСАЛ  2018  0.246901      B
48                      ОАО «РЖД»  2018  0.360763      B
37        Госкорпорация «Росатом»  2018  0.257337      B
23                       АО «ОМК»  2018  0.156730      B
19              АО «МХК «ЕвроХим»  2018  0.281166      B
8               «Сахалин Энерджи»  2018  0.284807      B
89                      ПАО «МТС»  2018  0.121317      B
150                 ПАО «ФосАгро»  2018  0.263061      B

2019
                         компания   год        s- letter
4                 «МЕТАЛЛОИНВЕСТ»  2019  0.280332      A
136              ПАО «Северсталь»  2019  0.238724      A
127           ПАО «СИБУР-Холдинг»  2019  0.229372      A
117              ПАО «Ростелеком»  2019  0.184867      A
100                    ПАО «НЛМК»  2019  0.240049      A
95             ПАО «НК «Роснефть»  2019  0.390194      A
76            ПАО «ИНТЕР РАО ЕЭС»  2019  0.223516      A
70                  ПАО «Газпром»  2019  0.479669      A
66   ПАО «ГМК «Норильский никель»  2019  0.245110      A
83                   ПАО «ЛУКОЙЛ»  2019  0.233532      A
33                  АФК «Система»  2019  0.273879      A
13                    АК «АЛРОСА»  2019  0.302191      A
55                       ОК РУСАЛ  2019  0.231878      B
140                     ПАО «ТМК»  2019  0.143645      B
9               «Сахалин Энерджи»  2019  0.285659      B
131        ПАО «Сбербанк России»   2019  0.296739      B
122                ПАО «РусГидро»  2019  0.281460      B
20              АО «МХК «ЕвроХим»  2019  0.271714      B
111                   ПАО «Полюс»  2019  0.135945      B
105                 ПАО «НОВАТЭК»  2019  0.249474      B
24                       АО «ОМК»  2019  0.158088      B
29                      АО «СУЭК»  2019  0.467886      B
90                      ПАО «МТС»  2019  0.156698      B
86                     ПАО «ММК»   2019  0.111287      B
142                ПАО «Татнефть»  2019  0.343672      B
79                    ПАО «КАМАЗ»  2019  0.164274      B
49                      ОАО «РЖД»  2019  0.225641      B
60                 ПАО «АЭРОФЛОТ»  2019  0.205702      B
151                 ПАО «ФосАгро»  2019  0.295678      B

2020
                         компания   год        s- letter
123                ПАО «РусГидро»  2020  0.190986      A
87                     ПАО «ММК»   2020  0.221478      A
84                   ПАО «ЛУКОЙЛ»  2020  0.256497      A
77            ПАО «ИНТЕР РАО ЕЭС»  2020  0.254913      A
71                  ПАО «Газпром»  2020  0.462888      A
67   ПАО «ГМК «Норильский никель»  2020  0.116942      A
118              ПАО «Ростелеком»  2020  0.167715      A
101                    ПАО «НЛМК»  2020  0.254928      A
128           ПАО «СИБУР-Холдинг»  2020  0.197706      A
96             ПАО «НК «Роснефть»  2020  0.392898      A
137              ПАО «Северсталь»  2020  0.231930      A
34                  АФК «Система»  2020  0.263780      A
30                      АО «СУЭК»  2020  0.524886      A
14                    АК «АЛРОСА»  2020  0.329526      A
5                 «МЕТАЛЛОИНВЕСТ»  2020  0.299296      A
112                   ПАО «Полюс»  2020  0.064332      B
108              ПАО «Полиметалл»  2020  0.361483      B
141                     ПАО «ТМК»  2020  0.125311      B
143                ПАО «Татнефть»  2020  0.334564      B
106                 ПАО «НОВАТЭК»  2020  0.280190      B
147              ПАО «Транснефть»  2020  0.174040      B
132        ПАО «Сбербанк России»   2020  0.277448      B
1                «Банк ВТБ» (ПАО)  2020  0.261009      B
80                    ПАО «КАМАЗ»  2020  0.167469      B
152                 ПАО «ФосАгро»  2020  0.275017      B
61                 ПАО «АЭРОФЛОТ»  2020  0.186739      B
56                       ОК РУСАЛ  2020  0.234791      B
50                      ОАО «РЖД»  2020  0.196033      B
45               Московская Биржа  2020  0.257123      B
43                         Магнит  2020  0.470244      B
40                     Группа ЛСР  2020  0.034126      B
38        Госкорпорация «Росатом»  2020  0.313066      B
25                       АО «ОМК»  2020  0.112019      B
21              АО «МХК «ЕвроХим»  2020  0.294969      B
10              «Сахалин Энерджи»  2020  0.307583      B
91                      ПАО «МТС»  2020  0.131571      B
154                 Петропавловск  2020  0.284767      B

2021
                           компания   год        s- letter
153                   ПАО «ФосАгро»  2021  0.291269      A
85                     ПАО «ЛУКОЙЛ»  2021  0.277338      A
97               ПАО «НК «Роснефть»  2021  0.429405      A
102                      ПАО «НЛМК»  2021  0.284994      A
51                        ОАО «РЖД»  2021  0.229645      A
109                ПАО «Полиметалл»  2021  0.070196      A
114                   ПАО «Россети»  2021  0.218196      A
119                ПАО «Ростелеком»  2021  0.200429      A
124                  ПАО «РусГидро»  2021  0.220665      A
35                    АФК «Система»  2021  0.283531      A
31                        АО «СУЭК»  2021  0.603272      A
138                ПАО «Северсталь»  2021  0.256156      A
144                  ПАО «Татнефть»  2021  0.355731      A
15                      АК «АЛРОСА»  2021  0.193138      A
6                   «МЕТАЛЛОИНВЕСТ»  2021  0.351157      A
149                 ПАО «Уралкалий»  2021  0.241342      A
72                    ПАО «Газпром»  2021  0.417314      A
133          ПАО «Сбербанк России»   2021  0.000000      B
0                   X5 Retail Group  2021  0.280810      B
62                   ПАО «АЭРОФЛОТ»  2021  0.267697      B
57                         ОК РУСАЛ  2021  0.223149      B
44                           Магнит  2021  0.236643      B
22                АО «МХК «ЕвроХим»  2021  0.304006      B
73                    ПАО «Газпром»  2021  0.417314      B
92                        ПАО «МТС»  2021  0.204221     B+
107                   ПАО «НОВАТЭК»  2021  0.334828     B+
46                 Московская Биржа  2021  0.291678     B+
113                     ПАО «Полюс»  2021  0.186113     B+
41                       Группа ЛСР  2021  0.021833     B+
39          Госкорпорация «Росатом»  2021  0.336984     B+
26                         АО «ОМК»  2021  0.193585     B+
63   ПАО «ВЫМПЕЛКОМ» / БРЕНД БИЛАЙН  2021  0.343518     B+
52             ОАО «Сургутнефтегаз»  2021  0.389112      C
42    Группа компаний «Детский мир»  2021  0.550640      C

In [196]:
df = pd.read_csv('reports_info_esg2.csv', index_col=0)
df = df.drop(['сектор', 'тип отчета', 'ссылка на отчет'], axis=1)
# df = df[df['год'].apply(len) == 4]
df['год'] = df['год'].apply(lambda x: x.split(', '))
df = df.explode('год').reset_index(drop=True)
df['год'] = df['год'].astype(int)
df = df.groupby(by=['компания', 'год']).sum().reset_index()
df.head()

,компания,год,E_Общие,E_Биоразнообразие,E_Вода,E_Газ,E_Климат,E_Отходы,E_Экологический менеджмент,E_Энергия,...,S_Охрана здоровья,S_Профсоюзы и коллективные договоры,S_Трудовые отношения,G_Антикоррупция,G_Дивиденды и акционеры,G_Инновации,G_Лидерство,G_Отчетность и прозрачность,G_Управление рисками,G_Эффективность и производительность
0,Abbott,2012,0.02,0.01,0.00,0.00,0.01,0.01,0.01,0.01,...,0.10,0.02,0.04,0.02,0.02,0.01,0.03,0.04,0.02,0.03
1,Abbott,2013,0.02,0.01,0.00,0.00,0.01,0.01,0.01,0.01,...,0.10,0.02,0.04,0.02,0.02,0.01,0.03,0.04,0.02,0.03
2,"Alcoa, Inc.",2004,0.02,0.01,0.01,0.00,0.01,0.03,0.01,0.01,...,0.00,0.03,0.03,0.02,0.02,0.00,0.02,0.02,0.02,0.03
3,"Alcoa, Inc.",2006,0.05,0.02,0.02,0.01,0.02,0.01,0.03,0.03,...,0.01,0.04,0.06,0.03,0.04,0.01,0.04,0.05,0.03,0.05
4,BELUGA GROUP,2020,0.04,0.01,0.02,0.00,0.03,0.02,0.03,0.03,...,0.01,0.05,0.07,0.05,0.03,0.02,0.06,0.06,0.03,0.05

In [197]:
df['res'] = df[e_topics + s_topics + g_topics].sum(axis=1)
df.drop(e_topics + s_topics + g_topics, axis=1, inplace=True)
df.head()

       компания   год   res
0        Abbott  2012  0.66
1        Abbott  2013  0.66
2   Alcoa, Inc.  2004  0.44
3   Alcoa, Inc.  2006  0.82
4  BELUGA GROUP  2020  0.98

In [198]:
df = pd.merge(df, rspp_df, on=['компания', 'год'], how='inner')
df.head()

           компания   год   res letter
0   X5 Retail Group  2021  0.70      B
1  «Банк ВТБ» (ПАО)  2020  0.75      B
2   «МЕТАЛЛОИНВЕСТ»  2017  0.74      A
3   «МЕТАЛЛОИНВЕСТ»  2018  0.51      A
4   «МЕТАЛЛОИНВЕСТ»  2019  0.82      A

In [199]:
for year, df_grouped in df.groupby(by=['год']):
    print(year)
    print(df_grouped.sort_values(by=['letter']))
    print()

2017
                         компания   год   res letter
2                 «МЕТАЛЛОИНВЕСТ»  2017  0.74      A
134              ПАО «Северсталь»  2017  0.67      A
125           ПАО «СИБУР-Холдинг»  2017  0.66      A
93             ПАО «НК «Роснефть»  2017  1.00      A
81                   ПАО «ЛУКОЙЛ»  2017  0.65      A
64   ПАО «ГМК «Норильский никель»  2017  0.66      A
53                       ОК РУСАЛ  2017  0.61      A
74            ПАО «ИНТЕР РАО ЕЭС»  2017  0.50      A
36        Госкорпорация «Росатом»  2017  0.67      A
27                      АО «СУЭК»  2017  0.60      A
11                    АК «АЛРОСА»  2017  0.46      A
7               «Сахалин Энерджи»  2017  0.87      B
129        ПАО «Сбербанк России»   2017  0.80      B
120                ПАО «РусГидро»  2017  0.57      B
115              ПАО «Ростелеком»  2017  0.49      B
103                 ПАО «НОВАТЭК»  2017  0.80      B
98                     ПАО «НЛМК»  2017  0.68      B
16              АО «Зарубежнефть»  2017  0.60      B
88                      ПАО «МТС»  2017  0.44      B
18              АО «МХК «ЕвроХим»  2017  0.74      B
78                    ПАО «КАМАЗ»  2017  0.14      B
145              ПАО «Транснефть»  2017  0.43      B
68                  ПАО «Газпром»  2017  1.33      B
58                 ПАО «АЭРОФЛОТ»  2017  0.45      B
47                      ОАО «РЖД»  2017  0.59      B
148               ПАО «Уралкалий»  2017  0.85      B

2018
                         компания   год   res letter
3                 «МЕТАЛЛОИНВЕСТ»  2018  0.51      A
82                   ПАО «ЛУКОЙЛ»  2018  0.62      A
69                  ПАО «Газпром»  2018  1.34      A
65   ПАО «ГМК «Норильский никель»  2018  0.63      A
116              ПАО «Ростелеком»  2018  0.48      A
32                  АФК «Система»  2018  1.37      A
126           ПАО «СИБУР-Холдинг»  2018  0.69      A
135              ПАО «Северсталь»  2018  0.61      A
17              АО «Зарубежнефть»  2018  0.44      A
12                    АК «АЛРОСА»  2018  0.85      A
28                      АО «СУЭК»  2018  0.58      A
94             ПАО «НК «Роснефть»  2018  1.11      A
130        ПАО «Сбербанк России»   2018  0.83      B
99                     ПАО «НЛМК»  2018  0.71      B
121                ПАО «РусГидро»  2018  0.65      B
110                   ПАО «Полюс»  2018  0.00      B
104                 ПАО «НОВАТЭК»  2018  0.67      B
139                     ПАО «ТМК»  2018  0.36      B
75            ПАО «ИНТЕР РАО ЕЭС»  2018  0.68      B
146              ПАО «Транснефть»  2018  0.42      B
59                 ПАО «АЭРОФЛОТ»  2018  0.54      B
54                       ОК РУСАЛ  2018  0.66      B
48                      ОАО «РЖД»  2018  1.10      B
37        Госкорпорация «Росатом»  2018  0.70      B
23                       АО «ОМК»  2018  0.43      B
19              АО «МХК «ЕвроХим»  2018  0.80      B
8               «Сахалин Энерджи»  2018  0.86      B
89                      ПАО «МТС»  2018  0.30      B
150                 ПАО «ФосАгро»  2018  0.77      B

2019
                         компания   год   res letter
4                 «МЕТАЛЛОИНВЕСТ»  2019  0.82      A
136              ПАО «Северсталь»  2019  0.67      A
127           ПАО «СИБУР-Холдинг»  2019  0.63      A
117              ПАО «Ростелеком»  2019  0.52      A
100                    ПАО «НЛМК»  2019  0.73      A
95             ПАО «НК «Роснефть»  2019  1.09      A
76            ПАО «ИНТЕР РАО ЕЭС»  2019  0.67      A
70                  ПАО «Газпром»  2019  1.26      A
66   ПАО «ГМК «Норильский никель»  2019  0.69      A
83                   ПАО «ЛУКОЙЛ»  2019  0.65      A
33                  АФК «Система»  2019  0.72      A
13                    АК «АЛРОСА»  2019  0.90      A
55                       ОК РУСАЛ  2019  0.64      B
140                     ПАО «ТМК»  2019  0.41      B
9               «Сахалин Энерджи»  2019  0.83      B
131        ПАО «Сбербанк России»   2019  0.85      B
122                ПАО «РусГидро»  2019  0.83      B
20              АО «МХК «ЕвроХим»  2019  0.76      B
111                   ПАО «Полюс»  2019  0.10      B
105                 ПАО «НОВАТЭК»  2019  0.70      B
24                       АО «ОМК»  2019  0.45      B
29                      АО «СУЭК»  2019  1.43      B
90                      ПАО «МТС»  2019  0.42      B
86                     ПАО «ММК»   2019  0.30      B
142                ПАО «Татнефть»  2019  1.04      B
79                    ПАО «КАМАЗ»  2019  0.43      B
49                      ОАО «РЖД»  2019  0.62      B
60                 ПАО «АЭРОФЛОТ»  2019  0.61      B
151                 ПАО «ФосАгро»  2019  0.85      B

2020
                         компания   год   res letter
123                ПАО «РусГидро»  2020  0.55      A
87                     ПАО «ММК»   2020  0.65      A
84                   ПАО «ЛУКОЙЛ»  2020  0.67      A
77            ПАО «ИНТЕР РАО ЕЭС»  2020  0.76      A
71                  ПАО «Газпром»  2020  1.17      A
67   ПАО «ГМК «Норильский никель»  2020  0.30      A
118              ПАО «Ростелеком»  2020  0.46      A
101                    ПАО «НЛМК»  2020  0.78      A
128           ПАО «СИБУР-Холдинг»  2020  0.56      A
96             ПАО «НК «Роснефть»  2020  1.11      A
137              ПАО «Северсталь»  2020  0.66      A
34                  АФК «Система»  2020  0.72      A
30                      АО «СУЭК»  2020  1.67      A
14                    АК «АЛРОСА»  2020  0.96      A
5                 «МЕТАЛЛОИНВЕСТ»  2020  0.89      A
112                   ПАО «Полюс»  2020  0.15      B
108              ПАО «Полиметалл»  2020  1.00      B
141                     ПАО «ТМК»  2020  0.36      B
143                ПАО «Татнефть»  2020  1.01      B
106                 ПАО «НОВАТЭК»  2020  0.79      B
147              ПАО «Транснефть»  2020  0.49      B
132        ПАО «Сбербанк России»   2020  0.81      B
1                «Банк ВТБ» (ПАО)  2020  0.75      B
80                    ПАО «КАМАЗ»  2020  0.47      B
152                 ПАО «ФосАгро»  2020  0.79      B
61                 ПАО «АЭРОФЛОТ»  2020  0.54      B
56                       ОК РУСАЛ  2020  0.65      B
50                      ОАО «РЖД»  2020  0.53      B
45               Московская Биржа  2020  0.75      B
43                         Магнит  2020  1.48      B
40                     Группа ЛСР  2020  0.04      B
38        Госкорпорация «Росатом»  2020  0.86      B
25                       АО «ОМК»  2020  0.28      B
21              АО «МХК «ЕвроХим»  2020  0.84      B
10              «Сахалин Энерджи»  2020  0.87      B
91                      ПАО «МТС»  2020  0.34      B
154                 Петропавловск  2020  0.78      B

2021
                           компания   год   res letter
153                   ПАО «ФосАгро»  2021  0.73      A
85                     ПАО «ЛУКОЙЛ»  2021  0.68      A
97               ПАО «НК «Роснефть»  2021  1.08      A
102                      ПАО «НЛМК»  2021  0.78      A
51                        ОАО «РЖД»  2021  0.56      A
109                ПАО «Полиметалл»  2021  0.14      A
114                   ПАО «Россети»  2021  0.56      A
119                ПАО «Ростелеком»  2021  0.51      A
124                  ПАО «РусГидро»  2021  0.54      A
35                    АФК «Система»  2021  0.65      A
31                        АО «СУЭК»  2021  1.72      A
138                ПАО «Северсталь»  2021  0.64      A
144                  ПАО «Татнефть»  2021  0.94      A
15                      АК «АЛРОСА»  2021  0.46      A
6                   «МЕТАЛЛОИНВЕСТ»  2021  0.95      A
149                 ПАО «Уралкалий»  2021  0.59      A
72                    ПАО «Газпром»  2021  0.98      A
133          ПАО «Сбербанк России»   2021  0.00      B
0                   X5 Retail Group  2021  0.70      B
62                   ПАО «АЭРОФЛОТ»  2021  0.65      B
57                         ОК РУСАЛ  2021  0.57      B
44                           Магнит  2021  0.60      B
22                АО «МХК «ЕвроХим»  2021  0.78      B
73                    ПАО «Газпром»  2021  0.98      B
92                        ПАО «МТС»  2021  0.48     B+
107                   ПАО «НОВАТЭК»  2021  0.88     B+
46                 Московская Биржа  2021  0.76     B+
113                     ПАО «Полюс»  2021  0.33     B+
41                       Группа ЛСР  2021  0.02     B+
39          Госкорпорация «Росатом»  2021  0.84     B+
26                         АО «ОМК»  2021  0.47     B+
63   ПАО «ВЫМПЕЛКОМ» / БРЕНД БИЛАЙН  2021  0.85     B+
52             ОАО «Сургутнефтегаз»  2021  0.78      C
42    Группа компаний «Детский мир»  2021  1.64      C

### Пытаемся обучить модели

In [321]:
df = pd.read_csv('reports_info_esg2.csv', index_col=0)
df = df.drop(['сектор', 'тип отчета', 'ссылка на отчет'], axis=1)
# df = df[df['год'].apply(len) == 4]
df['год'] = df['год'].apply(lambda x: x.split(', '))
df = df.explode('год').reset_index(drop=True)
df['год'] = df['год'].astype(int)
df = df.groupby(by=['компания', 'год']).sum().reset_index()
df = pd.merge(df, rspp_df, on=['компания', 'год'], how='inner')
df['letter'] = df['letter'].apply(lambda x: int(x == 'A'))
df.head()

,компания,год,E_Общие,E_Биоразнообразие,E_Вода,E_Газ,E_Климат,E_Отходы,E_Экологический менеджмент,E_Энергия,...,S_Профсоюзы и коллективные договоры,S_Трудовые отношения,G_Антикоррупция,G_Дивиденды и акционеры,G_Инновации,G_Лидерство,G_Отчетность и прозрачность,G_Управление рисками,G_Эффективность и производительность,letter
0,X5 Retail Group,2021,0.03,0.01,0.01,0.01,0.03,0.02,0.02,0.02,...,0.03,0.04,0.03,0.02,0.01,0.03,0.04,0.03,0.04,0
1,«Банк ВТБ» (ПАО),2020,0.02,0.01,0.00,0.00,0.02,0.01,0.01,0.02,...,0.01,0.04,0.02,0.06,0.02,0.06,0.05,0.06,0.05,0
2,«МЕТАЛЛОИНВЕСТ»,2017,0.02,0.01,0.01,0.00,0.02,0.01,0.02,0.02,...,0.02,0.04,0.03,0.12,0.01,0.03,0.03,0.03,0.03,1
3,«МЕТАЛЛОИНВЕСТ»,2018,0.02,0.01,0.01,0.00,0.02,0.01,0.02,0.01,...,0.02,0.03,0.02,0.06,0.01,0.02,0.02,0.02,0.02,1
4,«МЕТАЛЛОИНВЕСТ»,2019,0.03,0.01,0.01,0.01,0.02,0.01,0.03,0.02,...,0.03,0.04,0.03,0.12,0.01,0.03,0.03,0.03,0.03,1

In [322]:
df.shape

(155, 30)

In [323]:
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import mean_squared_error, mean_absolute_error, roc_auc_score, accuracy_score, f1_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegressionCV
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

In [325]:
df_train, df_test = train_test_split(df, test_size=30, random_state=42)

In [326]:
X_train, y_train = df_train.drop(['компания', 'год', 'letter'], axis=1), df_train.letter
X_test, y_test = df_test.drop(['компания', 'год', 'letter'], axis=1), df_test.letter

In [306]:
model = CatBoostClassifier(
    random_seed=42, verbose=False
)
clf = make_pipeline(StandardScaler(), model)

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)

In [307]:
print('CatBoost:')
print('MSE: ', mean_squared_error(y_pred, y_test))
print('MAE: ', mean_absolute_error(y_pred, y_test))
print('ROC_AUC: ', roc_auc_score(y_test, y_pred_proba[:, 1]))
print('Accuracy: ', accuracy_score(y_pred, y_test))
print('F1: ', f1_score(y_pred, y_test))

CatBoost:
MSE:  0.2
MAE:  0.2
ROC_AUC:  0.8839285714285714
Accuracy:  0.8
F1:  0.7692307692307692

In [291]:
model = RandomForestClassifier(random_state=42)

In [292]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)

In [293]:
print('Random Forest:')
print('MSE: ', mean_squared_error(y_pred, y_test))
print('MAE: ', mean_absolute_error(y_pred, y_test))
print('ROC_AUC: ', roc_auc_score(y_test, y_pred_proba[:, 1]))
print('Accuracy: ', accuracy_score(y_pred, y_test))
print('F1: ', f1_score(y_pred, y_test))

Random Forest:
MSE:  0.16666666666666666
MAE:  0.16666666666666666
ROC_AUC:  0.8638392857142857
Accuracy:  0.8333333333333334
F1:  0.8

In [294]:
model = AdaBoostClassifier(random_state=42)

In [295]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)

In [296]:
print('AdaBoostClassifier:')
print('MSE: ', mean_squared_error(y_pred, y_test))
print('MAE: ', mean_absolute_error(y_pred, y_test))
print('ROC_AUC: ', roc_auc_score(y_test, y_pred_proba[:, 1]))
print('Accuracy: ', accuracy_score(y_pred, y_test))
print('F1: ', f1_score(y_pred, y_test))

AdaBoostClassifier:
MSE:  0.3333333333333333
MAE:  0.3333333333333333
ROC_AUC:  0.6741071428571428
Accuracy:  0.6666666666666666
F1:  0.5833333333333334

In [327]:
models = {
    'CatBoost': CatBoostClassifier(random_seed=42, verbose=False),
    'Random Forest': RandomForestClassifier(random_state=42),
    'AdaBoost Classifier': AdaBoostClassifier(random_state=42),
    'Linear SVM': SVC(kernel="linear", C=0.025, probability=True, random_state=42),
    'RBF SVM': SVC(gamma=2, C=1, probability=True, random_state=42),
    'Neural Net': MLPClassifier(alpha=1, max_iter=1000, random_state=42),
    'logit': LogisticRegressionCV(cv=5, random_state=42)
}

results_df = pd.DataFrame(columns=['MSE', 'MAE', 'ROC_AUC', 'Accuracy', 'F1'])

for model_name, model in models.items():
    clf = make_pipeline(StandardScaler(), model)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    y_pred_proba = clf.predict_proba(X_test)
    results_df.loc[model_name, :] = [mean_squared_error(y_pred, y_test),
                                     mean_absolute_error(y_pred, y_test),
                                     roc_auc_score(y_test, y_pred_proba[:, 1]),
                                     accuracy_score(y_pred, y_test),
                                     f1_score(y_pred, y_test)]

In [328]:
results_df.head(10)

                          MSE       MAE   ROC_AUC  Accuracy        F1
CatBoost                  0.2       0.2  0.883929       0.8  0.769231
Random Forest        0.166667  0.166667  0.857143  0.833333       0.8
AdaBoost Classifier  0.333333  0.333333  0.674107  0.666667  0.583333
Linear SVM                0.2       0.2  0.790179       0.8  0.769231
RBF SVM              0.466667  0.466667  0.102679  0.533333       0.0
Neural Net           0.233333  0.233333  0.763393  0.766667  0.740741
logit                0.266667  0.266667  0.741071  0.733333  0.733333

In [330]:
clf = make_pipeline(StandardScaler(), 
                    LogisticRegressionCV(cv=5, random_state=42))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)[:, 1]
[mean_squared_error(y_pred, y_test),
 mean_absolute_error(y_pred, y_test),
 roc_auc_score(y_test, y_pred_proba),
 accuracy_score(y_pred, y_test),
 f1_score(y_pred, y_test)]

[0.26666666666666666,
 0.26666666666666666,
 0.7410714285714286,
 0.7333333333333333,
 0.7333333333333334]

In [331]:
df_test['logit_proba'] = y_pred_proba
df_test.head()

,компания,год,E_Общие,E_Биоразнообразие,E_Вода,E_Газ,E_Климат,E_Отходы,E_Экологический менеджмент,E_Энергия,...,S_Трудовые отношения,G_Антикоррупция,G_Дивиденды и акционеры,G_Инновации,G_Лидерство,G_Отчетность и прозрачность,G_Управление рисками,G_Эффективность и производительность,letter,logit_proba
81,ПАО «ЛУКОЙЛ»,2017,0.04,0.02,0.02,0.03,0.02,0.02,0.04,0.03,...,0.04,0.02,0.03,0.01,0.03,0.03,0.03,0.04,1,0.724250
142,ПАО «Татнефть»,2019,0.04,0.02,0.01,0.04,0.04,0.02,0.05,0.04,...,0.04,0.03,0.08,0.01,0.06,0.07,0.06,0.08,0,0.303981
31,АО «СУЭК»,2021,0.07,0.04,0.02,0.02,0.11,0.04,0.06,0.07,...,0.10,0.06,0.07,0.02,0.08,0.10,0.09,0.10,1,0.766815
29,АО «СУЭК»,2019,0.05,0.04,0.02,0.02,0.12,0.03,0.05,0.05,...,0.07,0.05,0.06,0.02,0.07,0.08,0.08,0.09,0,0.970464
118,ПАО «Ростелеком»,2020,0.02,0.01,0.01,0.00,0.01,0.01,0.01,0.02,...,0.03,0.02,0.02,0.01,0.03,0.02,0.02,0.03,1,0.310125

In [335]:
df_logit_res = df_test[['компания', 'год', 'logit_proba', 'letter']].sort_values(by='logit_proba', ascending=False).reset_index(drop=True)
df_logit_res.head(10)

              компания   год  logit_proba  letter
0            АО «СУЭК»  2019     0.970464       0
1        ПАО «Газпром»  2017     0.937307       0
2   ПАО «НК «Роснефть»  2019     0.910183       1
3     ПАО «Северсталь»  2020     0.893297       1
4     ПАО «Северсталь»  2021     0.876686       1
5         ПАО «ЛУКОЙЛ»  2020     0.840730       1
6            АО «СУЭК»  2020     0.806066       1
7    «Сахалин Энерджи»  2019     0.772646       0
8            АО «СУЭК»  2021     0.766815       1
9  ПАО «ИНТЕР РАО ЕЭС»  2018     0.735643       0

In [336]:
clf = make_pipeline(StandardScaler(), 
                    SVC(kernel="linear", C=0.025, probability=True, random_state=42))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)[:, 1]
[mean_squared_error(y_pred, y_test),
 mean_absolute_error(y_pred, y_test),
 roc_auc_score(y_test, y_pred_proba),
 accuracy_score(y_pred, y_test),
 f1_score(y_pred, y_test)]

[0.2, 0.2, 0.7901785714285714, 0.8, 0.7692307692307692]

In [337]:
df_test['linear_svc_proba'] = y_pred_proba
df_test.head()

,компания,год,E_Общие,E_Биоразнообразие,E_Вода,E_Газ,E_Климат,E_Отходы,E_Экологический менеджмент,E_Энергия,...,G_Антикоррупция,G_Дивиденды и акционеры,G_Инновации,G_Лидерство,G_Отчетность и прозрачность,G_Управление рисками,G_Эффективность и производительность,letter,logit_proba,linear_svc_proba
81,ПАО «ЛУКОЙЛ»,2017,0.04,0.02,0.02,0.03,0.02,0.02,0.04,0.03,...,0.02,0.03,0.01,0.03,0.03,0.03,0.04,1,0.724250,0.543638
142,ПАО «Татнефть»,2019,0.04,0.02,0.01,0.04,0.04,0.02,0.05,0.04,...,0.03,0.08,0.01,0.06,0.07,0.06,0.08,0,0.303981,0.465525
31,АО «СУЭК»,2021,0.07,0.04,0.02,0.02,0.11,0.04,0.06,0.07,...,0.06,0.07,0.02,0.08,0.10,0.09,0.10,1,0.766815,0.713813
29,АО «СУЭК»,2019,0.05,0.04,0.02,0.02,0.12,0.03,0.05,0.05,...,0.05,0.06,0.02,0.07,0.08,0.08,0.09,0,0.970464,0.872286
118,ПАО «Ростелеком»,2020,0.02,0.01,0.01,0.00,0.01,0.01,0.01,0.02,...,0.02,0.02,0.01,0.03,0.02,0.02,0.03,1,0.310125,0.349367

In [338]:
df_linear_svc_res = df_test[['компания', 'год', 'linear_svc_proba', 'letter']].sort_values(by='linear_svc_proba', ascending=False).reset_index(drop=True)
df_linear_svc_res.head(10)

             компания   год  linear_svc_proba  letter
0       ПАО «Газпром»  2017          0.878008       0
1           АО «СУЭК»  2019          0.872286       0
2       ПАО «Газпром»  2018          0.787918       1
3  ПАО «НК «Роснефть»  2019          0.737591       1
4           АО «СУЭК»  2021          0.713813       1
5           АО «СУЭК»  2020          0.694159       1
6        ПАО «ЛУКОЙЛ»  2020          0.661365       1
7  ПАО «НК «Роснефть»  2017          0.657028       1
8    ПАО «Северсталь»  2021          0.640019       1
9    ПАО «Северсталь»  2020          0.631801       1

In [339]:
clf = make_pipeline(StandardScaler(), 
                    CatBoostClassifier(random_seed=42, verbose=False))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)[:, 1]
[mean_squared_error(y_pred, y_test),
 mean_absolute_error(y_pred, y_test),
 roc_auc_score(y_test, y_pred_proba),
 accuracy_score(y_pred, y_test),
 f1_score(y_pred, y_test)]

[0.2, 0.2, 0.8839285714285714, 0.8, 0.7692307692307692]

In [340]:
df_test['catboost_proba'] = y_pred_proba
df_catboost_res = df_test[['компания', 'год', 'catboost_proba', 'letter']].sort_values(by='catboost_proba', ascending=False).reset_index(drop=True)
df_catboost_res.head(10)

             компания   год  catboost_proba  letter
0    ПАО «Северсталь»  2020        0.887911       1
1  ПАО «НК «Роснефть»  2019        0.875180       1
2       ПАО «Газпром»  2017        0.847009       0
3    ПАО «Северсталь»  2021        0.846409       1
4       ПАО «Газпром»  2018        0.797479       1
5    ПАО «Ростелеком»  2019        0.777448       1
6        ПАО «ЛУКОЙЛ»  2020        0.755432       1
7  ПАО «НК «Роснефть»  2017        0.728732       1
8        ПАО «ЛУКОЙЛ»  2017        0.719999       1
9         АК «АЛРОСА»  2018        0.704874       1